export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const GET_ALL_NUMBERS = 'GET_ALL_PHONE';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const GET_ALL_EMAILS = 'GET_ALL_EMAILS';
export const TWILIO_TOKEN = 'TWILIO_TOKEN';
