export const APP_NAME="ProspectX 1.0"
export const SIGN_IN="Sign in"
export const ENTER_EMAIL_PASSWORD = "Enter your email address and password"
export const EMAIL_LABEL = "Enter your email"
export const EMAIL_PLACEHOLDER = 'Email'
export const PASSWORD_LABEL="Password"
export const FORGOT_PASSWORD_TITLE="Forgot Password"
export const PASSWORD_PLACEHOLDER = "Password"
export const LOGIN_BUTTON_TITTLE = "Login"
export const FORGOT_PASSWORD_LABEL="Forgot Password?"
export const DESC_TEXT="Enter your email address and we’ll send you a link to reset your password."
export const SUBMIT = "Submit"
export const RESEND_CODE="Code not recieved? Resend code."
export const RESET_PASSWORD_TITLE="Reset Password"
export const RESET_PASSWORD_SUBTEXT="Enter your new password."
export const ENTER_PASSWORD_LABEL="New password"
export const ENTER_CONFIRM_PASSWORD_LABEL="Confirm Password"
export const RESET_BUTTON_TEXT="Reset"
export const INCOMING_NUMBER="+1 258 258 258"
export const INCOMING_STATUS="Ringing..."
export const SWIPEBTNTITLE="Slide to answer"
export const MUTE_TEXT="Mute"
export const SPEAKER_TEXT="Speaker"
export const PROFILE_SETTINGS = 'Settings'
export const PROFILE_CHANGE_PASS="Change Password"
export const PROFILE_LOGOUT="Logout"
export const CHANGE_PASS_TITLE='Change Password'
export const CHANGE_PASS_DESC="Your new password must contain 8 letters."
export const OLD_PASSWORD='Old Password'
export const NEW_PASSWORD='New Password'
export const CONFIRM_PASSWORD='Confirm Password'